[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
monad = "https://rpc.monad.xyz"

[etherscan]
monad = { key = "${ETHERSCAN_API_KEY}", url = "https://api.monadvision.com/api" }
